on:
  push:
    branches:
      - main
name: "Build and Release"
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.3'
          
      - name: Firebase
        run: |
           sudo npm install node
           sudo npm install -g firebase-tools
           sudo firebase login:ci
           
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk
      
#       - name: Check_file & Path
#         run: pwd && ls -la  
          
      - name: Check_file & Path
        run: ls -la build/app/outputs/flutter-apk/app-release.apk && pwd
        
#       - name: Firebase
#         run: |
#            npm install node
#            npm install -g firebase-tools
#            firebase login:ci
      
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.GITHUB}}
          
          
#       - name: Push to firebase app distribution
#         uses: wzieba/Firebase-Distribution-Github-Action@v1
#         with:
#           appId: ${{secrets.FIREBASE_APP_ID}}
#           token: ${{secrets.FIREBASE_TOKEN}}
#           group: testers
#           #file: build/app/outputs/apk/release/app-release.apk

      - name: App Center
        uses: wzieba/AppCenter-Github-Action@v1.3.3
        with:
         appName: kumarvineet011/Flutter_android_ios
         token: ${{secrets.APP_CENTER_TOKEN}}
         group: test
         file: build/app/outputs/flutter-apk/app-release.apk
         notifyTesters: true
         debug: false
